import * as Path from 'path'
import { spawn } from 'child_process'
import {
  HKEY,
  RegistryValueType,
  createKey,
  enumerateValuesSafe,
  setValue,
} from 'registry-js'
import { pathExists } from '../lib/path-exists'
import {
  ContextMenuSurface,
  IObservedContextMenuEntry,
  IWindowsContextMenuApplyResult,
  IWindowsContextMenuEnvironment,
  IWindowsContextMenuLabels,
  IWindowsContextMenuPlan,
  IWindowsContextMenuState,
  WindowsContextMenuEntryId,
  WindowsContextMenuEntryIds,
  buildRegDeleteArguments,
  buildWindowsContextMenuPlan,
  buildWindowsContextMenuRemoval,
  summarizeWindowsContextMenuState,
  unsupportedWindowsContextMenuState,
} from '../lib/windows-context-menu'

/**
 * Applies the payloads generated by `lib/windows-context-menu` to the live
 * per-user registry, and probes the host for the paths those payloads need.
 *
 * The split is deliberate: every decision (what to write, whether the current
 * state matches, what to delete) lives in the pure module and is unit-tested
 * without a registry; this file only performs I/O. Nothing here is exercised by
 * the test suite, because doing so would mean writing to the tester's registry.
 *
 * Writes go through `registry-js`, which the app already depends on. It has no
 * delete API, so removal shells out to `reg.exe` with a generated argv (never a
 * concatenated command string) and `shell: false`.
 */

/** Common opencode install locations to check when it is not on PATH. */
function candidateOpencodePaths(): ReadonlyArray<string> {
  const localAppData = process.env.LOCALAPPDATA
  const appData = process.env.APPDATA
  const userProfile = process.env.USERPROFILE
  const candidates: Array<string> = []

  if (localAppData !== undefined) {
    candidates.push(
      Path.join(localAppData, 'Programs', 'opencode', 'opencode.exe'),
      Path.join(localAppData, 'opencode', 'bin', 'opencode.exe')
    )
  }
  if (appData !== undefined) {
    // npm's global bin directory, where `npm i -g opencode-ai` lands.
    candidates.push(
      Path.join(appData, 'npm', 'opencode.cmd'),
      Path.join(appData, 'npm', 'opencode.exe')
    )
  }
  if (userProfile !== undefined) {
    candidates.push(
      Path.join(userProfile, '.opencode', 'bin', 'opencode.exe'),
      Path.join(userProfile, '.bun', 'bin', 'opencode.exe')
    )
  }

  return candidates
}

/**
 * Resolve `opencode` on PATH honouring PATHEXT, then fall back to the known
 * install locations. Returns null when nothing usable is found, which is what
 * suppresses the menu entry entirely.
 */
async function findOpencode(): Promise<string | null> {
  const pathext = (process.env.PATHEXT ?? '.COM;.EXE;.BAT;.CMD')
    .split(';')
    .filter(Boolean)
  const dirs = (process.env.Path ?? process.env.PATH ?? '')
    .split(';')
    .filter(Boolean)

  for (const dir of dirs) {
    for (const ext of pathext) {
      const candidate = Path.join(dir, `opencode${ext}`)
      if (await pathExists(candidate)) {
        return candidate
      }
    }
  }

  for (const candidate of candidateOpencodePaths()) {
    if (await pathExists(candidate)) {
      return candidate
    }
  }

  return null
}

/** Windows Terminal ships as an app-execution alias in WindowsApps. */
async function findWindowsTerminal(): Promise<string | null> {
  const localAppData = process.env.LOCALAPPDATA
  if (localAppData === undefined) {
    return null
  }
  const candidate = Path.join(
    localAppData,
    'Microsoft',
    'WindowsApps',
    'wt.exe'
  )
  return (await pathExists(candidate)) ? candidate : null
}

function cmdPath(): string {
  const systemRoot =
    process.env.SystemRoot ?? process.env.WINDIR ?? 'C:\\Windows'
  return Path.join(systemRoot, 'System32', 'cmd.exe')
}

/**
 * Probe the host and build the environment the payload generator needs.
 *
 * `appPath` is `process.execPath` — the real running executable, so an entry
 * written by a portable or side-by-side install points back at that install
 * rather than at a guessed Program Files location.
 */
export async function probeWindowsContextMenuEnvironment(
  labels: IWindowsContextMenuLabels
): Promise<IWindowsContextMenuEnvironment> {
  const [opencodePath, windowsTerminalPath] = await Promise.all([
    findOpencode(),
    findWindowsTerminal(),
  ])

  return {
    appPath: process.execPath,
    opencodePath,
    windowsTerminalPath,
    cmdPath: cmdPath(),
    labels,
  }
}

/** Read the `command` default value under a verb key, or null when absent. */
function readCommand(key: string): string | null {
  try {
    const values = enumerateValuesSafe(
      HKEY.HKEY_CURRENT_USER,
      `${key}\\command`
    )
    const entry = values.find(value => value.name === '')
    if (entry === undefined || typeof entry.data !== 'string') {
      return null
    }
    return entry.data
  } catch {
    // `enumerateValuesSafe` swallows a missing key, but a permissions failure
    // or a malformed value should read as "not installed" rather than crash the
    // settings pane.
    return null
  }
}

function observeEntries(): ReadonlyArray<IObservedContextMenuEntry> {
  return WindowsContextMenuEntryIds.map(id => {
    const removals = buildWindowsContextMenuRemoval([id])
    const commands: Record<ContextMenuSurface, string | null> = {
      directory: null,
      background: null,
    }
    for (const removal of removals) {
      const surface: ContextMenuSurface = removal.key.includes('\\Background\\')
        ? 'background'
        : 'directory'
      commands[surface] = readCommand(removal.key)
    }
    return { id, commands }
  })
}

/**
 * Read the current state of every entry.
 *
 * Registry contents are the single source of truth: a toggle reflects what
 * Explorer will actually show, so an entry removed by another tool (or an
 * install path invalidated by an app update) is reported honestly instead of
 * echoing a stale preference.
 */
export async function getWindowsContextMenuState(
  labels: IWindowsContextMenuLabels
): Promise<IWindowsContextMenuState> {
  if (process.platform !== 'win32') {
    return unsupportedWindowsContextMenuState()
  }

  const environment = await probeWindowsContextMenuEnvironment(labels)
  const plan = buildWindowsContextMenuPlan(environment)
  return summarizeWindowsContextMenuState(plan, observeEntries())
}

function installEntry(
  plan: IWindowsContextMenuPlan,
  id: WindowsContextMenuEntryId
) {
  const entry = plan.entries.find(candidate => candidate.id === id)
  if (entry === undefined) {
    const reason = plan.unavailable.find(item => item.id === id)?.reason
    throw new Error(
      reason === 'opencode-not-found'
        ? 'opencode was not found on this computer'
        : 'The application path could not be determined'
    )
  }

  for (const key of entry.keys) {
    if (!createKey(HKEY.HKEY_CURRENT_USER, key.key)) {
      throw new Error(`Could not create registry key HKCU\\${key.key}`)
    }
    for (const value of key.values) {
      if (
        !setValue(
          HKEY.HKEY_CURRENT_USER,
          key.key,
          value.name,
          RegistryValueType.REG_SZ,
          value.data
        )
      ) {
        throw new Error(
          `Could not write registry value "${value.name}" under HKCU\\${key.key}`
        )
      }
    }
  }
}

/** Run one generated `reg.exe delete`. Resolves even when the key was absent. */
function runRegDelete(args: ReadonlyArray<string>): Promise<void> {
  return new Promise((resolve, reject) => {
    const child = spawn(
      Path.join(cmdPath(), '..', 'reg.exe'),
      args as string[],
      {
        // Never a shell: the argv is generated and must not be re-parsed.
        shell: false,
        stdio: 'ignore',
        windowsHide: true,
      }
    )
    child.on('error', reject)
    child.on('exit', code => {
      // `reg delete` exits 1 when the key does not exist, which is success for
      // an uninstall — the desired end state is "absent" either way.
      if (code === 0 || code === 1) {
        resolve()
      } else {
        reject(new Error(`reg.exe delete failed with exit code ${code}`))
      }
    })
  })
}

async function removeEntry(id: WindowsContextMenuEntryId): Promise<void> {
  for (const removal of buildWindowsContextMenuRemoval([id])) {
    await runRegDelete(buildRegDeleteArguments(removal.hive, removal.key))
  }
}

/**
 * Install or remove one entry and report the outcome.
 *
 * A failure is returned rather than thrown so the settings pane can show a
 * per-entry message while leaving the other toggle usable.
 */
export async function setWindowsContextMenuEntryInstalled(
  id: WindowsContextMenuEntryId,
  installed: boolean,
  labels: IWindowsContextMenuLabels
): Promise<IWindowsContextMenuApplyResult> {
  if (process.platform !== 'win32') {
    return {
      id,
      installed: false,
      error: 'Windows context menu entries are only available on Windows',
    }
  }

  try {
    if (installed) {
      const environment = await probeWindowsContextMenuEnvironment(labels)
      installEntry(buildWindowsContextMenuPlan(environment), id)
    } else {
      await removeEntry(id)
    }
    return { id, installed, error: null }
  } catch (error) {
    log.error(
      `Failed to ${installed ? 'install' : 'remove'} context menu entry ${id}`,
      error
    )
    return {
      id,
      installed: !installed,
      error:
        error instanceof Error
          ? error.message
          : 'The registry could not be updated',
    }
  }
}
