/**
 * Hand-written inventory of settings that use the shared progressive
 * explanation and truthful provenance component.
 *
 * This list is deliberately explicit. Source discovery cannot detect a
 * setting that disappeared entirely, so each newly covered setting is added
 * here in the same change as its control and focused proof.
 */
export const ImplementedSettingExplanationIds = [
  'accessibility-diff-check-marks',
  'accessibility-underline-links',
  'accounts-bitbucket-authorization',
  'accounts-bitbucket-username',
  'accounts-gitlab-authorization',
  'accounts-gitlab-server',
  'accounts-jira-authorization',
  'accounts-jira-deployment',
  'accounts-jira-email',
  'accounts-jira-server',
  'accounts-trello-api-key',
  'accounts-trello-authorization',
  'accounts-trello-server',
  'advanced-auto-switch-account',
  'advanced-browser-open-mode',
  'advanced-external-credential-helper',
  'advanced-large-repository-auto-detect',
  'advanced-large-repository-auto-repack',
  'advanced-repository-indicators',
  'advanced-usage-reporting',
  'advanced-verbose-logging',
  'advanced-windows-openssh',
  'agent-access-enabled',
  'agent-access-mode',
  'app-identity-custom-logo-image',
  'app-identity-bold',
  'app-identity-brand-gap',
  'app-identity-character-spacing',
  'app-identity-display-name',
  'app-identity-font-family',
  'app-identity-font-size',
  'app-identity-font-weight',
  'app-identity-font-width',
  'app-identity-highlight',
  'app-identity-highlight-color',
  'app-identity-italic',
  'app-identity-letter-case',
  'app-identity-logo-border',
  'app-identity-logo-border-color',
  'app-identity-logo-choice',
  'app-identity-logo-color',
  'app-identity-logo-inset',
  'app-identity-logo-rotation',
  'app-identity-logo-size',
  'app-identity-logo-shadow',
  'app-identity-logo-shape',
  'app-identity-name-color',
  'app-identity-name-opacity',
  'app-identity-show-logo',
  'app-identity-smallCaps',
  'app-identity-strikeThrough',
  'app-identity-text-effect',
  'app-identity-underline',
  'ai-default-repository-eligibility',
  'ai-master-switch',
  'ai-provider-byok',
  'ai-provider-github-copilot',
  'attention-focus',
  'attention-low-stimulation',
  'attention-time-awareness',
  'automation-account-auto-commit-push-enabled',
  'automation-account-auto-commit-push-interval',
  'automation-account-auto-pull-enabled',
  'automation-account-auto-pull-interval',
  'automation-auto-commit-push-enabled',
  'automation-auto-commit-push-interval',
  'automation-auto-pull-enabled',
  'automation-auto-pull-interval',
  'appearance-auto-fit-zoom',
  'appearance-branch-sort',
  'appearance-date-format',
  'appearance-dialog-emoji',
  'appearance-funny-cantonese',
  'appearance-funny-english',
  'appearance-language-mode',
  'appearance-number-format',
  'appearance-prefer-absolute-dates',
  'appearance-show-branch-name',
  'appearance-show-recent-repositories',
  'appearance-tab-size',
  'appearance-time-format',
  'appearance-theme',
  'appearance-ui-scale',
  'copilot-always-resolve-conflicts',
  'copilot-commit-message-model',
  'copilot-conflict-resolution-model',
  'issue-reference-jira-cloud-item',
  'issue-reference-jira-cloud-scope',
  'issue-reference-jira-data-center-item',
  'issue-reference-jira-data-center-scope',
  'issue-reference-trello-item',
  'issue-reference-trello-scope',
  'git-author-email',
  'git-author-name',
  'git-default-branch-name',
  'git-hook-environment-cache',
  'git-hook-environment-enabled',
  'git-hook-environment-shell',
  'git-show-commit-identity',
  'attention-one-thing-at-a-time',
  'attention-momentum',
  'attention-next-action',
  'attention-momentum-defer-interval',
  'prompts-commit-length-warning',
  'prompts-confirm-checkout-commit',
  'prompts-confirm-commit-filtered-changes',
  'prompts-confirm-commit-message-override',
  'prompts-confirm-discard-changes',
  'prompts-confirm-discard-permanently',
  'prompts-confirm-discard-stash',
  'prompts-confirm-force-push',
  'prompts-confirm-repository-removal',
  'prompts-confirm-undo-commit',
  'prompts-confirm-worktree-removal',
  'prompts-uncommitted-changes-strategy',
  'self-hosted-server-join-url',
  'self-hosted-server-public-origin',
  'self-hosted-server-saml-metadata',
  'scheduled-all-days',
  'scheduled-api-endpoint',
  'scheduled-appearance-accentPalette',
  'scheduled-appearance-elevation',
  'scheduled-appearance-highlight-features',
  'scheduled-appearance-monospaceFont',
  'scheduled-appearance-motion',
  'scheduled-appearance-repositoryListDensity',
  'scheduled-appearance-submoduleBackButtonLabel',
  'scheduled-appearance-submoduleBackButtonStyle',
  'scheduled-appearance-surfacePalette',
  'scheduled-appearance-tabCloseButtons',
  'scheduled-appearance-tabDensity',
  'scheduled-appearance-tabWidth',
  'scheduled-appearance-toolbarDensity',
  'scheduled-appearance-toolbarLabels',
  'scheduled-appearance-uiFont',
  'scheduled-appearance-updateProgressPalette',
  'scheduled-end-date',
  'scheduled-end-time',
  'scheduled-home-assistant-entity',
  'scheduled-home-assistant-token',
  'scheduled-home-assistant-url',
  'scheduled-language',
  'scheduled-rule-enabled',
  'scheduled-rule-label',
  'scheduled-start-date',
  'scheduled-start-time',
  'scheduled-theme',
  'scheduled-value-source',
  'scheduled-weekdays',
  'sound-quiet-hours-end',
  'sound-quiet-hours-start',
  'sound-repository-track',
  'status-hub-endpoint',
  'status-hub-authorization-replacement',
] as const

export type ImplementedSettingExplanationId =
  typeof ImplementedSettingExplanationIds[number]

export function assertImplementedSettingExplanationIds(
  ids: ReadonlyArray<string>
): void {
  const actual = [...ids].sort()
  const expected = [...ImplementedSettingExplanationIds].sort()
  if (
    actual.length !== expected.length ||
    actual.some((value, index) => value !== expected[index])
  ) {
    throw new Error(
      `Setting explanation inventory mismatch. Expected ${expected.join(
        ', '
      )}; received ${actual.join(', ')}.`
    )
  }
}
