/* eslint-disable no-sync */
import { execFileSync } from 'child_process'
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'fs'
import * as path from 'path'
import { deflateSync } from 'zlib'
import {
  ShellExtensionDllName,
  ShellExtensionArchitecture,
  buildShellExtensionManifest,
  formatX500Publisher,
} from '../app/src/lib/shell-extension-package'
import { getDistArchitecture } from './dist-info'

/**
 * Builds the Windows 11 shell-extension sparse package.
 *
 * Two artefacts land in `<out>/shell-extension`:
 *
 *  - `DesktopMaterialShellExtension.dll` — the in-process COM server compiled
 *    from `shell-extension/src/dllmain.cpp` with MSVC.
 *  - `AppxManifest.xml` — the sparse package manifest generated by the same
 *    module the app uses, so the CLSID and paths cannot drift.
 *
 * The package is registered loosely at runtime (`Add-AppxPackage -Register`)
 * rather than packed and signed, because trusting a self-signed certificate is
 * a machine-wide administrator action this project does not take. `makeappx` is
 * therefore not required to ship; it is only used by `--pack` for anyone who
 * wants a signable `.msix` to sign with a real certificate.
 *
 * The whole step is optional: when MSVC is unavailable the build logs and skips
 * it, and the app falls back to the classic context-menu verbs. A missing C++
 * toolchain must not break a JavaScript build.
 */

const projectRoot = path.resolve(__dirname, '..')
const sourceDir = path.join(projectRoot, 'shell-extension', 'src')

export type MsvcHostArchitecture = 'x64' | 'arm64'

export interface IMsvcToolchainCoordinates {
  readonly hostDirectory: 'Hostx64' | 'Hostarm64'
  readonly targetDirectory: ShellExtensionArchitecture
  readonly vcVarsArgument: string
  readonly linkerMachine: 'X64' | 'ARM64'
  readonly peMachine: number
}

/**
 * Map the app's target architecture onto the MSVC cross-toolchain contract.
 *
 * CI runs both product lanes on an x64 Windows host, so ARM64 must use the
 * `Hostx64\\arm64` compiler plus `vcvarsall x64_arm64`, not the native x64
 * compiler that happens to be first on PATH.
 */
export function getMsvcToolchainCoordinates(
  targetArchitecture: ShellExtensionArchitecture,
  hostArchitecture: MsvcHostArchitecture = process.arch === 'arm64'
    ? 'arm64'
    : 'x64'
): IMsvcToolchainCoordinates {
  return {
    hostDirectory: hostArchitecture === 'arm64' ? 'Hostarm64' : 'Hostx64',
    targetDirectory: targetArchitecture,
    vcVarsArgument:
      hostArchitecture === targetArchitecture
        ? targetArchitecture
        : `${hostArchitecture}_${targetArchitecture}`,
    linkerMachine: targetArchitecture === 'arm64' ? 'ARM64' : 'X64',
    peMachine: targetArchitecture === 'arm64' ? 0xaa64 : 0x8664,
  }
}

export interface IMsvcShellExtensionToolchain {
  readonly compilerPath: string
  readonly vcVarsAllPath: string
  readonly coordinates: IMsvcToolchainCoordinates
}

/** Locate a compiler and vcvars script from the same Visual Studio install. */
export function findMsvcToolchain(
  targetArchitecture: ShellExtensionArchitecture,
  visualStudioRoot = 'C:\\Program Files\\Microsoft Visual Studio',
  hostArchitecture: MsvcHostArchitecture = process.arch === 'arm64'
    ? 'arm64'
    : 'x64'
): IMsvcShellExtensionToolchain | null {
  if (process.platform !== 'win32' || !existsSync(visualStudioRoot)) {
    return null
  }

  const coordinates = getMsvcToolchainCoordinates(
    targetArchitecture,
    hostArchitecture
  )
  const candidates: Array<
    IMsvcShellExtensionToolchain & { readonly version: string }
  > = []

  for (const release of safeReadDir(visualStudioRoot)) {
    for (const edition of safeReadDir(path.join(visualStudioRoot, release))) {
      const installRoot = path.join(visualStudioRoot, release, edition)
      const vcVarsAllPath = path.join(
        installRoot,
        'VC',
        'Auxiliary',
        'Build',
        'vcvarsall.bat'
      )
      if (!existsSync(vcVarsAllPath)) {
        continue
      }

      const toolsRoot = path.join(installRoot, 'VC', 'Tools', 'MSVC')
      for (const version of safeReadDir(toolsRoot)) {
        const compilerPath = path.join(
          toolsRoot,
          version,
          'bin',
          coordinates.hostDirectory,
          coordinates.targetDirectory,
          'cl.exe'
        )
        if (existsSync(compilerPath)) {
          candidates.push({
            compilerPath,
            vcVarsAllPath,
            coordinates,
            version,
          })
        }
      }
    }
  }

  candidates.sort((a, b) =>
    a.version.localeCompare(b.version, undefined, { numeric: true })
  )
  const selected = candidates[candidates.length - 1]
  return selected === undefined
    ? null
    : {
        compilerPath: selected.compilerPath,
        vcVarsAllPath: selected.vcVarsAllPath,
        coordinates: selected.coordinates,
      }
}

/** Locate the newest Windows SDK `bin\<version>\x64` directory. */
export function findWindowsSdkBin(
  kitsRoot = 'C:\\Program Files (x86)\\Windows Kits\\10\\bin'
): string | null {
  if (!existsSync(kitsRoot)) {
    return null
  }
  const versions = safeReadDir(kitsRoot)
    .filter(name => /^10\.\d+\.\d+\.\d+$/.test(name))
    .filter(name => existsSync(path.join(kitsRoot, name, 'x64')))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

  return versions.length > 0
    ? path.join(kitsRoot, versions[versions.length - 1], 'x64')
    : null
}

function safeReadDir(directory: string): ReadonlyArray<string> {
  try {
    return readdirSync(directory, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => entry.name)
  } catch {
    return []
  }
}

/** Read the COFF machine field from a PE image without executing the file. */
export function readPortableExecutableMachine(image: Buffer): number {
  if (image.length < 0x40 || image.readUInt16LE(0) !== 0x5a4d) {
    throw new Error('Shell extension output is not a valid MZ executable')
  }

  const peOffset = image.readUInt32LE(0x3c)
  if (
    peOffset > image.length - 6 ||
    image.readUInt32LE(peOffset) !== 0x00004550
  ) {
    throw new Error('Shell extension output has no valid PE header')
  }

  return image.readUInt16LE(peOffset + 4)
}

/** Prove that the compiler emitted the architecture the package declares. */
export function validateShellExtensionMachine(
  image: Buffer,
  architecture: ShellExtensionArchitecture
): void {
  const actual = readPortableExecutableMachine(image)
  const expected = getMsvcToolchainCoordinates(architecture).peMachine
  if (actual !== expected) {
    throw new Error(
      `compiler emitted PE machine 0x${actual.toString(
        16
      )}; expected 0x${expected.toString(16)} for ${architecture}`
    )
  }
}

/**
 * Encode a solid-colour RGBA PNG.
 *
 * MSIX requires PNG logo assets, but the app only ships `.ico`/`.icns`, and
 * this package declares `AppListEntry="none"` so its tiles are never rendered
 * anywhere a user can see. Rather than adding an image-conversion dependency
 * for images nobody looks at, the required assets are generated here — Node's
 * own zlib is all a valid PNG needs.
 */
export function encodeSolidPng(
  size: number,
  rgba: readonly [number, number, number, number]
): Buffer {
  const chunk = (type: string, data: Buffer) => {
    const length = Buffer.alloc(4)
    length.writeUInt32BE(data.length)
    const typeAndData = Buffer.concat([Buffer.from(type, 'ascii'), data])
    const crc = Buffer.alloc(4)
    crc.writeUInt32BE(crc32(typeAndData))
    return Buffer.concat([length, typeAndData, crc])
  }

  const header = Buffer.alloc(13)
  header.writeUInt32BE(size, 0)
  header.writeUInt32BE(size, 4)
  header[8] = 8 // bit depth
  header[9] = 6 // colour type: RGBA
  header[10] = 0
  header[11] = 0
  header[12] = 0

  // Each scanline is prefixed with a filter byte (0 = none).
  const stride = size * 4
  const raw = Buffer.alloc((stride + 1) * size)
  for (let y = 0; y < size; y++) {
    const rowStart = y * (stride + 1)
    raw[rowStart] = 0
    for (let x = 0; x < size; x++) {
      const pixel = rowStart + 1 + x * 4
      raw[pixel] = rgba[0]
      raw[pixel + 1] = rgba[1]
      raw[pixel + 2] = rgba[2]
      raw[pixel + 3] = rgba[3]
    }
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

const crcTable = (() => {
  const table = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    }
    table[n] = c >>> 0
  }
  return table
})()

function crc32(buffer: Buffer): number {
  let crc = 0xffffffff
  for (const byte of buffer) {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ 0xffffffff) >>> 0
}

/** Write the logo assets the manifest declares. */
function writePackageAssets(outputDirectory: string) {
  const assetsDir = path.join(outputDirectory, 'Assets')
  mkdirSync(assetsDir, { recursive: true })
  // Desktop Material's seed colour, so the placeholder is at least on-brand.
  const colour = [0x4a, 0x5a, 0xa8, 0xff] as const
  for (const [name, size] of [
    ['StoreLogo.png', 50],
    ['Square150x150Logo.png', 150],
    ['Square44x44Logo.png', 44],
  ] as const) {
    writeFileSync(path.join(assetsDir, name), encodeSolidPng(size, colour))
  }
}

export interface IShellExtensionBuildResult {
  readonly built: boolean
  readonly reason?: string
  readonly outputDirectory?: string
}

export interface IShellExtensionBuildOptions {
  readonly pack?: boolean
  readonly architecture?: ShellExtensionArchitecture
  /** Test/downstream override; production discovery uses Visual Studio's root. */
  readonly visualStudioRoot?: string
}

/** Compile the DLL and write the manifest beside it. */
export function buildShellExtension(
  outputRoot: string,
  options: IShellExtensionBuildOptions = {}
): IShellExtensionBuildResult {
  if (process.platform !== 'win32') {
    return { built: false, reason: 'not building on Windows' }
  }

  const outputDirectory = path.join(outputRoot, 'shell-extension')
  // This directory is wholly generated. Remove it before every early return so
  // a missing ARM64 toolchain can never leave a prior x64 DLL available for the
  // packaging step to pick up.
  rmSync(outputDirectory, { recursive: true, force: true })

  const architecture = options.architecture ?? getDistArchitecture()
  const toolchain = findMsvcToolchain(architecture, options.visualStudioRoot)
  if (toolchain === null) {
    return {
      built: false,
      reason: `no Visual Studio C++ ${architecture} build tools found`,
    }
  }

  mkdirSync(outputDirectory, { recursive: true })

  const fail = (reason: string): IShellExtensionBuildResult => {
    // Never let a partial or wrong-architecture native build look registrable.
    rmSync(outputDirectory, { recursive: true, force: true })
    return { built: false, reason }
  }

  const source = path.join(sourceDir, 'dllmain.cpp')
  const dllPath = path.join(outputDirectory, ShellExtensionDllName)

  mkdirSync(path.join(outputDirectory, 'obj'), { recursive: true })

  // vcvarsall must run in the same shell as cl.exe to export INCLUDE/LIB, so the
  // two are written to one batch file. Passing them as a `cmd /c` string
  // instead would have Node escape the embedded quotes and break every path
  // containing a space — which "Program Files" always does.
  const scriptPath = path.join(outputDirectory, 'build-shell-extension.bat')
  writeFileSync(
    scriptPath,
    [
      '@echo off',
      `call "${toolchain.vcVarsAllPath}" ${toolchain.coordinates.vcVarsArgument} || exit /b 1`,
      [
        `"${toolchain.compilerPath}"`,
        '/nologo',
        '/std:c++17',
        '/EHsc',
        '/O2',
        '/DUNICODE',
        '/D_UNICODE',
        '/LD',
        `"${source}"`,
        `/Fe:"${dllPath}"`,
        // The object directory needs a trailing separator, doubled so it does
        // not escape the closing quote under the MSVC command-line parse.
        `/Fo:"${path.join(outputDirectory, 'obj')}\\\\"`,
        '/link',
        'shlwapi.lib',
        'ole32.lib',
        'shell32.lib',
        'user32.lib',
        `/MACHINE:${toolchain.coordinates.linkerMachine}`,
        `/DEF:"${path.join(sourceDir, 'exports.def')}"`,
      ].join(' '),
      'exit /b %ERRORLEVEL%',
    ].join('\r\n'),
    'utf8'
  )

  try {
    execFileSync('cmd.exe', ['/c', scriptPath], {
      stdio: 'inherit',
      cwd: outputDirectory,
    })
  } catch (error) {
    return fail(
      `cl.exe failed: ${error instanceof Error ? error.message : String(error)}`
    )
  }

  if (!existsSync(dllPath)) {
    return fail('compiler produced no DLL')
  }

  try {
    validateShellExtensionMachine(readFileSync(dllPath), architecture)
  } catch (error) {
    return fail(
      error instanceof Error
        ? error.message
        : 'could not validate shell extension architecture'
    )
  }

  // Intermediates would otherwise ship inside the package directory, where
  // everything present is content the sparse package exposes.
  rmSync(path.join(outputDirectory, 'obj'), { recursive: true, force: true })
  rmSync(scriptPath, { force: true })
  for (const leftover of [
    'dllmain.obj',
    'DesktopMaterialShellExtension.exp',
    'DesktopMaterialShellExtension.lib',
  ]) {
    rmSync(path.join(outputDirectory, leftover), { force: true })
  }

  writePackageAssets(outputDirectory)

  writeFileSync(
    path.join(outputDirectory, 'AppxManifest.xml'),
    buildShellExtensionManifest({
      architecture,
      // A loose registration does not verify the publisher, but the value must
      // still parse as an X.500 name.
      publisher: formatX500Publisher('GitHub, Inc.'),
      publisherDisplayName: 'GitHub, Inc.',
      // Every path resolves against the external location (the app's install
      // directory), so each is prefixed with this package's own subdirectory.
      dllPath: `shell-extension\\${ShellExtensionDllName}`,
      executablePath: 'GitHubDesktop.exe',
      assetsPath: 'shell-extension\\Assets',
    }),
    'utf8'
  )

  if (options.pack === true) {
    packSparsePackage(outputDirectory)
  }

  return { built: true, outputDirectory }
}

/**
 * Pack a signable `.msix`. Not used by the default build — the shipped route is
 * loose registration — but kept so a real signing certificate can be applied by
 * anyone who has one.
 */
function packSparsePackage(outputDirectory: string) {
  const sdkBin = findWindowsSdkBin()
  if (sdkBin === null) {
    console.log('Skipping MSIX pack: no Windows SDK found')
    return
  }
  execFileSync(
    path.join(sdkBin, 'makeappx.exe'),
    [
      'pack',
      '/d',
      outputDirectory,
      '/p',
      path.join(outputDirectory, 'DesktopMaterialShellExtension.msix'),
      '/nv',
      '/o',
    ],
    { stdio: 'inherit' }
  )
}

if (require.main === module) {
  const outputRoot = process.argv[2] ?? path.join(projectRoot, 'out')
  const result = buildShellExtension(outputRoot, {
    pack: process.argv.includes('--pack'),
  })
  if (result.built) {
    console.log(`Shell extension built into ${result.outputDirectory}`)
  } else {
    // Never fatal: the classic context-menu verbs remain the fallback.
    console.log(`Shell extension not built (${result.reason})`)
  }
}
