/* eslint-disable no-sync */
import { execFileSync } from 'child_process'
import { existsSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'fs'
import * as path from 'path'
import { deflateSync } from 'zlib'
import {
  ShellExtensionDllName,
  buildShellExtensionManifest,
  formatX500Publisher,
} from '../app/src/lib/shell-extension-package'

/**
 * Builds the Windows 11 shell-extension sparse package.
 *
 * Two artefacts land in `<out>/shell-extension`:
 *
 *  - `DesktopMaterialShellExtension.dll` — the in-process COM server compiled
 *    from `shell-extension/src/dllmain.cpp` with MSVC.
 *  - `AppxManifest.xml` — the sparse package manifest generated by the same
 *    module the app uses, so the CLSID and paths cannot drift.
 *
 * The package is registered loosely at runtime (`Add-AppxPackage -Register`)
 * rather than packed and signed, because trusting a self-signed certificate is
 * a machine-wide administrator action this project does not take. `makeappx` is
 * therefore not required to ship; it is only used by `--pack` for anyone who
 * wants a signable `.msix` to sign with a real certificate.
 *
 * The whole step is optional: when MSVC is unavailable the build logs and skips
 * it, and the app falls back to the classic context-menu verbs. A missing C++
 * toolchain must not break a JavaScript build.
 */

const projectRoot = path.resolve(__dirname, '..')
const sourceDir = path.join(projectRoot, 'shell-extension', 'src')

/** Locate the newest MSVC `cl.exe` for the host architecture. */
export function findMsvcCompiler(
  visualStudioRoot = 'C:\\Program Files\\Microsoft Visual Studio'
): string | null {
  if (process.platform !== 'win32' || !existsSync(visualStudioRoot)) {
    return null
  }

  const candidates: Array<string> = []
  for (const release of safeReadDir(visualStudioRoot)) {
    for (const edition of safeReadDir(path.join(visualStudioRoot, release))) {
      const toolsRoot = path.join(
        visualStudioRoot,
        release,
        edition,
        'VC',
        'Tools',
        'MSVC'
      )
      for (const version of safeReadDir(toolsRoot)) {
        const candidate = path.join(
          toolsRoot,
          version,
          'bin',
          'Hostx64',
          'x64',
          'cl.exe'
        )
        if (existsSync(candidate)) {
          candidates.push(candidate)
        }
      }
    }
  }

  // Sort so the highest MSVC version wins rather than whichever the filesystem
  // happened to list first.
  candidates.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  return candidates.length > 0 ? candidates[candidates.length - 1] : null
}

/** Locate the newest Windows SDK `bin\<version>\x64` directory. */
export function findWindowsSdkBin(
  kitsRoot = 'C:\\Program Files (x86)\\Windows Kits\\10\\bin'
): string | null {
  if (!existsSync(kitsRoot)) {
    return null
  }
  const versions = safeReadDir(kitsRoot)
    .filter(name => /^10\.\d+\.\d+\.\d+$/.test(name))
    .filter(name => existsSync(path.join(kitsRoot, name, 'x64')))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))

  return versions.length > 0
    ? path.join(kitsRoot, versions[versions.length - 1], 'x64')
    : null
}

function safeReadDir(directory: string): ReadonlyArray<string> {
  try {
    return readdirSync(directory, { withFileTypes: true })
      .filter(entry => entry.isDirectory())
      .map(entry => entry.name)
  } catch {
    return []
  }
}

/**
 * Locate `vcvars64.bat`, which sets the INCLUDE/LIB variables the compiler
 * needs. Invoking the compiler without it fails on the very first `#include`.
 */
function findVcVars(
  visualStudioRoot = 'C:\\Program Files\\Microsoft Visual Studio'
): string | null {
  for (const release of safeReadDir(visualStudioRoot)) {
    for (const edition of safeReadDir(path.join(visualStudioRoot, release))) {
      const candidate = path.join(
        visualStudioRoot,
        release,
        edition,
        'VC',
        'Auxiliary',
        'Build',
        'vcvars64.bat'
      )
      if (existsSync(candidate)) {
        return candidate
      }
    }
  }
  return null
}

/**
 * Encode a solid-colour RGBA PNG.
 *
 * MSIX requires PNG logo assets, but the app only ships `.ico`/`.icns`, and
 * this package declares `AppListEntry="none"` so its tiles are never rendered
 * anywhere a user can see. Rather than adding an image-conversion dependency
 * for images nobody looks at, the required assets are generated here — Node's
 * own zlib is all a valid PNG needs.
 */
export function encodeSolidPng(
  size: number,
  rgba: readonly [number, number, number, number]
): Buffer {
  const chunk = (type: string, data: Buffer) => {
    const length = Buffer.alloc(4)
    length.writeUInt32BE(data.length)
    const typeAndData = Buffer.concat([Buffer.from(type, 'ascii'), data])
    const crc = Buffer.alloc(4)
    crc.writeUInt32BE(crc32(typeAndData))
    return Buffer.concat([length, typeAndData, crc])
  }

  const header = Buffer.alloc(13)
  header.writeUInt32BE(size, 0)
  header.writeUInt32BE(size, 4)
  header[8] = 8 // bit depth
  header[9] = 6 // colour type: RGBA
  header[10] = 0
  header[11] = 0
  header[12] = 0

  // Each scanline is prefixed with a filter byte (0 = none).
  const stride = size * 4
  const raw = Buffer.alloc((stride + 1) * size)
  for (let y = 0; y < size; y++) {
    const rowStart = y * (stride + 1)
    raw[rowStart] = 0
    for (let x = 0; x < size; x++) {
      const pixel = rowStart + 1 + x * 4
      raw[pixel] = rgba[0]
      raw[pixel + 1] = rgba[1]
      raw[pixel + 2] = rgba[2]
      raw[pixel + 3] = rgba[3]
    }
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk('IHDR', header),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ])
}

const crcTable = (() => {
  const table = new Uint32Array(256)
  for (let n = 0; n < 256; n++) {
    let c = n
    for (let k = 0; k < 8; k++) {
      c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1
    }
    table[n] = c >>> 0
  }
  return table
})()

function crc32(buffer: Buffer): number {
  let crc = 0xffffffff
  for (const byte of buffer) {
    crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8)
  }
  return (crc ^ 0xffffffff) >>> 0
}

/** Write the logo assets the manifest declares. */
function writePackageAssets(outputDirectory: string) {
  const assetsDir = path.join(outputDirectory, 'Assets')
  mkdirSync(assetsDir, { recursive: true })
  // Desktop Material's seed colour, so the placeholder is at least on-brand.
  const colour = [0x4a, 0x5a, 0xa8, 0xff] as const
  for (const [name, size] of [
    ['StoreLogo.png', 50],
    ['Square150x150Logo.png', 150],
    ['Square44x44Logo.png', 44],
  ] as const) {
    writeFileSync(path.join(assetsDir, name), encodeSolidPng(size, colour))
  }
}

export interface IShellExtensionBuildResult {
  readonly built: boolean
  readonly reason?: string
  readonly outputDirectory?: string
}

/** Compile the DLL and write the manifest beside it. */
export function buildShellExtension(
  outputRoot: string,
  options: { readonly pack?: boolean } = {}
): IShellExtensionBuildResult {
  if (process.platform !== 'win32') {
    return { built: false, reason: 'not building on Windows' }
  }

  const vcvars = findVcVars()
  if (vcvars === null) {
    return { built: false, reason: 'no Visual Studio C++ build tools found' }
  }

  const outputDirectory = path.join(outputRoot, 'shell-extension')
  rmSync(outputDirectory, { recursive: true, force: true })
  mkdirSync(outputDirectory, { recursive: true })

  const source = path.join(sourceDir, 'dllmain.cpp')
  const dllPath = path.join(outputDirectory, ShellExtensionDllName)

  mkdirSync(path.join(outputDirectory, 'obj'), { recursive: true })

  // vcvars64 must run in the same shell as cl.exe to export INCLUDE/LIB, so the
  // two are written to one batch file. Passing them as a `cmd /c` string
  // instead would have Node escape the embedded quotes and break every path
  // containing a space — which "Program Files" always does.
  const scriptPath = path.join(outputDirectory, 'build-shell-extension.bat')
  writeFileSync(
    scriptPath,
    [
      '@echo off',
      `call "${vcvars}" || exit /b 1`,
      [
        'cl.exe',
        '/nologo',
        '/std:c++17',
        '/EHsc',
        '/O2',
        '/DUNICODE',
        '/D_UNICODE',
        '/LD',
        `"${source}"`,
        `/Fe:"${dllPath}"`,
        // The object directory needs a trailing separator, doubled so it does
        // not escape the closing quote under the MSVC command-line parse.
        `/Fo:"${path.join(outputDirectory, 'obj')}\\\\"`,
        '/link',
        'shlwapi.lib',
        'ole32.lib',
        'shell32.lib',
        'user32.lib',
        `/DEF:"${path.join(sourceDir, 'exports.def')}"`,
      ].join(' '),
      'exit /b %ERRORLEVEL%',
    ].join('\r\n'),
    'utf8'
  )

  try {
    execFileSync('cmd.exe', ['/c', scriptPath], {
      stdio: 'inherit',
      cwd: outputDirectory,
    })
  } catch (error) {
    return {
      built: false,
      reason: `cl.exe failed: ${
        error instanceof Error ? error.message : String(error)
      }`,
    }
  }

  if (!existsSync(dllPath)) {
    return { built: false, reason: 'compiler produced no DLL' }
  }

  // Intermediates would otherwise ship inside the package directory, where
  // everything present is content the sparse package exposes.
  rmSync(path.join(outputDirectory, 'obj'), { recursive: true, force: true })
  rmSync(scriptPath, { force: true })
  for (const leftover of [
    'dllmain.obj',
    'DesktopMaterialShellExtension.exp',
    'DesktopMaterialShellExtension.lib',
  ]) {
    rmSync(path.join(outputDirectory, leftover), { force: true })
  }

  writePackageAssets(outputDirectory)

  writeFileSync(
    path.join(outputDirectory, 'AppxManifest.xml'),
    buildShellExtensionManifest({
      // A loose registration does not verify the publisher, but the value must
      // still parse as an X.500 name.
      publisher: formatX500Publisher('GitHub, Inc.'),
      publisherDisplayName: 'GitHub, Inc.',
      // Every path resolves against the external location (the app's install
      // directory), so each is prefixed with this package's own subdirectory.
      dllPath: `shell-extension\\${ShellExtensionDllName}`,
      executablePath: 'GitHubDesktop.exe',
      assetsPath: 'shell-extension\\Assets',
    }),
    'utf8'
  )

  if (options.pack === true) {
    packSparsePackage(outputDirectory)
  }

  return { built: true, outputDirectory }
}

/**
 * Pack a signable `.msix`. Not used by the default build — the shipped route is
 * loose registration — but kept so a real signing certificate can be applied by
 * anyone who has one.
 */
function packSparsePackage(outputDirectory: string) {
  const sdkBin = findWindowsSdkBin()
  if (sdkBin === null) {
    console.log('Skipping MSIX pack: no Windows SDK found')
    return
  }
  execFileSync(
    path.join(sdkBin, 'makeappx.exe'),
    [
      'pack',
      '/d',
      outputDirectory,
      '/p',
      path.join(outputDirectory, 'DesktopMaterialShellExtension.msix'),
      '/nv',
      '/o',
    ],
    { stdio: 'inherit' }
  )
}

if (require.main === module) {
  const outputRoot = process.argv[2] ?? path.join(projectRoot, 'out')
  const result = buildShellExtension(outputRoot, {
    pack: process.argv.includes('--pack'),
  })
  if (result.built) {
    console.log(`Shell extension built into ${result.outputDirectory}`)
  } else {
    // Never fatal: the classic context-menu verbs remain the fallback.
    console.log(`Shell extension not built (${result.reason})`)
  }
}
