"""Public GitHub integration API for Desktop Material TUI."""

from .client import GhClient
from .errors import (
    GitHubAuthenticationError,
    GitHubCliNotFoundError,
    GitHubCommandError,
    GitHubError,
    GitHubResponseError,
    GitHubResponseTooLargeError,
    GitHubScopeError,
    GitHubTimeoutError,
    GitHubUnsafeOperationError,
    GitHubValidationError,
)
from .models import (
    ActionReceipt,
    ExplorerResponse,
    GitHubAuthStatus,
    GitHubUser,
    Issue,
    IssueComment,
    IssueState,
    MergeMethod,
    Package,
    PackageVersion,
    Project,
    PullRequest,
    PullRequestMergeResult,
    PullRequestReview,
    PullRequestState,
    Release,
    ReleaseAsset,
    RepositoryRef,
    ReviewDecision,
    Workflow,
    WorkflowJob,
    WorkflowLogMetadata,
    WorkflowRun,
    WorkflowStep,
)
from .transport import GhProcessResult, GhTransport, SubprocessGhTransport

__all__ = [
    "ActionReceipt",
    "ExplorerResponse",
    "GhClient",
    "GhProcessResult",
    "GhTransport",
    "GitHubAuthStatus",
    "GitHubAuthenticationError",
    "GitHubCliNotFoundError",
    "GitHubCommandError",
    "GitHubError",
    "GitHubResponseError",
    "GitHubResponseTooLargeError",
    "GitHubScopeError",
    "GitHubTimeoutError",
    "GitHubUnsafeOperationError",
    "GitHubUser",
    "GitHubValidationError",
    "Issue",
    "IssueComment",
    "IssueState",
    "MergeMethod",
    "Package",
    "PackageVersion",
    "Project",
    "PullRequest",
    "PullRequestMergeResult",
    "PullRequestReview",
    "PullRequestState",
    "Release",
    "ReleaseAsset",
    "RepositoryRef",
    "ReviewDecision",
    "SubprocessGhTransport",
    "Workflow",
    "WorkflowJob",
    "WorkflowLogMetadata",
    "WorkflowRun",
    "WorkflowStep",
]
